Covid-19Radar/Covid19Radar

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hans.xlf
中国語（簡体字）の翻訳を少し修正をしました。 #52 
- 誤字の修正。
- 文言をもう少しNativeに近い使い方への修正。
- 一部半角の記号が使用されているため、標準の全角記号への修正。
- 機械翻訳の部分の加工。
> update: Chinese Simplified Translation

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.sv.xlf
There were a few weird sentences:
``` xml
<trans-unit id="DescriptionPageTextStep3Description" translate="yes" xml:space="preserve">
<source>Please manually change your status to "Positive" after verifying your phone number."Positive" Workflow , Now coordination with related parties.</source>
<target state="needs-review-translation" state-qualifier="mt-suggestion">Ändra din status till "Positiv" när du har verifierat ditt telefonnummer." Positivt" Arbetsflöde , Nu samordning med närstående.</target>
<note from="MultilingualBuild" annotates="source" priority="2">How it works page step 3 description</note>
</trans-unit>
```
I don't believe this to be true outside Japan:
``` xml
<trans-unit id="UserSettingPageTextStatusSettingsSMSInfo" translate="yes" xml:space="preserve">
<source>We will …
```
> translated (to Swedish) with questions

- Covid19Radar/Covid19Radar.Android/Properties/AndroidManifest.xml
* Fix minSdkVersion 23
Android Exposure Notification API need Android version 6.0 (API 23) or higher.
https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf
> Fix minSdkVersion 23

- Covid19Radar/Covid19Radar/Services/ExposureNotificationService.cs
App crashes #450 の修正として提案する変更です。
ExposureNotification が無効な時に`ExposureNotification.StopAsync()` を呼び出さないようにしました。
```
[x] Yes
[ ] No
```
```
[x] Bugfix
[ ] Feature
```
1. iOSの設定で COVID-19 Exposure Notifications をオフにしてアプリを起動
2. UserDataChanged 発生
3. クラッシュ?
実際のExposure Notifications APIの試験ができないのでこれで修正ができているのかどうか
> fix a crash on StopExposureNotification()

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hans.xlf
1. 初回のコミット f964000 は、「処理番号」を他の文言と合わせて、「数字码」に翻訳しました。
2. 2回目のコミット e250e33 に関しては、実際画面上の表示は正しくないため、文言を調整しました。
今画面上に表示されている文言は
> YYYY年MM月DD日**从**使用中
正しい表現は
> **从**YYYY年MM月DD日开始使用（他の表現もありますが）
**从**を文言の最初に持っていくことはできないので、下記のような表現できるように翻訳を変えました（違和感はないパタン）
```
YYYY年MM月DD日开始使用
```
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: i18n
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix some Chinese translation

- CONTRIBUTORS.md
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.en.xlf
The English version of the "submit consent page" is very difficult to understand at the beginning, and not understandable at all in the last paragraph. This PR tries to improve the translation based on the Japanese translation.
[ ] Yes
[x] No
[x] Bugfix
[ ] Feature
[x] Other... Please describe: localization improvement
It seems that English was used as the `source` language in the localization process, but lots of strings were machine translated from Japanese. I'm wondering if the localization to other languages was done correctly based on the English source.
> Improves English translation of consent submission screen

- CONTRIBUTORS.md
- Covid19Radar/Covid19Radar/Views/HelpPage/HelpMenuPage.xaml
- Covid19Radar/Covid19Radar/Views/HelpPage/HelpMenuPage.xaml.cs
* Deselect ListView item when back to  the help page #574 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
git clone https://github.com/koogawa/Covid19Radar
cd Covid19Radar
git checkout fix/issue-574 
```
Build!
```
```
- the app deselect an item in the help listview when the app navigated back to the help page.
> Fix #574 Deselect ListView item when back to  the help page

- Covid19Radar/Covid19Radar/Views/HelpPage/HelpMenuPage.xaml
- Covid19Radar/Covid19Radar/Views/MenuPage.xaml
* Fix https://github.com/Covid-19Radar/Covid19Radar/issues/603
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
git clone https://github.com/akeome/Covid19Radar
cd Covid19Radar
git checkout bugfix/hide-empty-cells
```
```
```
* Empty cells are not displayed on `MenuPage` and `HelpMenuPage` .
ScreenShots is here
* `MenuPage.xaml`
| Befor | After |
----|---- 
| <img src="https://user-images.githubusercontent.com/20479956/85330395-4c738f00-b50f-11ea-9878-1da21c481934.png"> | <img …
> Fix #603 Empty cell appears on the menu screen

- Covid19Radar/Covid19Radar/Services/ExposureNotificationService.cs
- Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
[Fix]Duplicate EN disable message.
ExposureNotificationService.UpdateStatusMessageAsync() が、
OnUserDataChanged と EnabledAsync() or DisabledAsync() とで2回呼び出されているのが原因。
OnUserDataChanged() に集約で。
> [Fix]Duplicate EN disable message.

- Covid19Radar/Covid19Radar/Services/UserDataService.cs
#602 の修正  
`current`に`userData`を代入しているだけなので、`userData`と`current`は同じ値になってしまい、更新処理が行われていなかった。  
`current `は、`Get()`で取得した新たなオブジェクトを代入するようにした
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
アプリの設定画面に遷移して、[接触の検出]と[通知]を両方ともOFFの状態からONに切り替えた後、他の画面に遷移して、再度、アプリの設定画面に遷移して、両方ともONであることを確認する
アプリの設定画面に再度遷移した時に、[接触の検出]と[通知]両方とも前に設定した状態が維持されていること
> 接触の検出と通知を同時に変更すると後に変更した方が反映されない

- Covid19Radar/Covid19Radar/Services/UserDataService.cs
- Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs
If UserData reset in Settings Page, StartDateTime is always displayed today.
> [Fix] If UserData reset in Settings Page, StartDateTime is always displayed today.

- Covid19Radar/Covid19Radar/Views/MenuPage.xaml
* #694 の修正
* #692 の修正の影響で、`OnPlatform`で、`BindingBase`を設定するようにしているのだが、iOSの場合は、`Color`を設定するようになっているので、`InvalidCastException`が発生していた
* iOSも`BindingBase`で設定するように修正した
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
iOSで起動して、ホーム画面から、サイドメニューを開く
* iOSでホーム画面を開いて、`InvalidCastException`が発生しないこと
* サイドメニュー画面のアイコンや、テキストの色が指定の色であること
> [iOS]ホーム画面で、InvalidCastExceptionが発生する

- Covid19Radar/Covid19Radar/Common/AppConstants.cs
- Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
- Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml
Change button state by a value of diagnosis uid. The user will be able to know what to do next depending on the input status of diagnosis UID.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: UI Improvement
```
```
cd [repo-name]
npm install
```
```
1. Open "陽性情報の登録" > "同意して陽性登録する"
2. Confirm that "登録する" is disabled in first.
3. Input arbitrary 1~7 digit numbers.
4. Confirm that "登録する" remains disabled.
5. Input arbitrary 8 digit numbers.
6. Confirm that "登録する" becomes enabled.
``` …
> Validating diagnosis uid in the NotifyOtherPage

- Covid19Radar/Covid19Radar/ViewModels/MenuPageViewModel.cs
- Covid19Radar/Covid19Radar/Views/MenuPage.xaml
* メニュー画面の選択セルの色が戻らない不具合を修正しました。
#660 対応
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* メニュー画面を表示して、任意のボタンをタップし、再度メニュー画面を表示しても、選択セルに色が付いていないこと。
> #660対応 メニュー画面の選択セルの色が戻らない不具合を修正

- Covid19Radar/Covid19Radar/App.xaml
* 陽性情報の登録ページにあるEntryの文字サイズが小さい。
利用者が番号を入力するので、もう少し文字サイズを大きくしてもよいのではと考えました。
Smallだった設定をDefaultに変更しました。
#629 対応
下記比較画像は、Issueに載せている画像と同じです。
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* 現時点でEntryの実装を行っているのは、陽性情報の登録ページのみ。
このページで文字を入力して確認する。
> #629対応 EntryのStyleの文字サイズをDefault変更

- Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
#724 について、登録待ちの表示をローディング表示に変更し、なおかつローディング表示開始から5秒後に以降の処理を進めるように変更しました。
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
#724 参照
* 登録待ちの表示のとき、ダイアログではなくLoading表示されること
* iOS 登録待ち表示(日本語)
* iOS 登録待ち表示(英語)
* Android 登録待ち表示(日本語) ※ タブレットサイズ
* Android 登録待ち表示(英語) ※ タブレットサイズ
> Fix #724, 登録待ちをLoading表示に変更＋ダイアログ表示のタイミングで5秒カウント開始

- Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Reverts Covid-19Radar/Covid19Radar#727
> Revert "Fix #724, 登録待ちをLoading表示に変更＋ダイアログ表示のタイミングで5秒カウント開始"

- CONTRIBUTORS.md
- README.ja.md
- README.md
* #755 README内の「開発環境の構築については、"こちらのドキュメント"を参照してください。」の部分でリンク切れが起きていたので修正しました。
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* README内の該当箇所のリンクをクリックして doc/Developer-Note.md に飛べること。
> Fix #755 : ReadMe内のリンク切れの修正

- Covid19Radar/Covid19Radar/Views/MenuPage.xaml
* #558 の修正
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
1. [設定] -> [アクセシビリティ] -> [画面表示とテキストサイズ] -> [さらに大きな文字]
2. フォントサイズを変更する
修正後、iOS では下図のように表示されます。
Xamarin.Formsのバージョンが 4.7.0.968 ですと、iOSシミュレータの場合ホーム画面に遷移するとクラッシュしてしまうため、一時的にXamarin.Formsのバージョンを  4.6.0.847 に下げて動作確認をおこないました。
> [iOS/Android] フォントサイズを大きくすると メニューの文字が見切れてしまう

- CONTRIBUTORS.md
- Covid19Radar/Covid19Radar/App.xaml.cs
- Covid19Radar/Covid19Radar/Common/AppUtils.cs
- Covid19Radar/Covid19Radar/Covid19Radar.csproj
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.en.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.ja.xlf
- Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
- Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.resx
- Covid19Radar/Covid19Radar/ViewModels/MenuPageViewModel.cs
- Covid19Radar/Covid19Radar/ViewModels/NewsPage/NewsPageViewModel.cs
- Covid19Radar/Covid19Radar/ViewModels/NewsPage/WebViewerPageViewModel.cs
- Covid19Radar/Covid19Radar/Views/NewsPage/NewsPage.xaml
- Covid19Radar/Covid19Radar/Views/NewsPage/NewsPage.xaml.cs
- Covid19Radar/Covid19Radar/Views/NewsPage/WebViewerPage.xaml
- Covid19Radar/Covid19Radar/Views/NewsPage/WebViewerPage.xaml.cs
* 最新情報を表示する為のページを追加しました。(#770)
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
1. メニューを開く
2. 「最新情報」をタップ
3. 「最新情報をGoogleで検索」をタップ
* Google検索で最新の情報を調べる事ができます。
* 不具合で内部ブラウザを閉じてから左上の矢印をタップしないと最新情報ページに戻りません。
4. 「対策ダッシュボード」をタップ
* https://stopcovid19.jp が開かれます。
> Solve Issue #770: Added News Page

- Covid19Radar/Covid19Radar/ViewModels/HelpPage/InqueryPageViewModel.cs
* #760 に対応。不具合対応を行う際に、どの機種でどのOSでどのバージョンで不具合が発生しているかを切り分けるためにiOSかAndroidかなどOSの情報とアプリのバージョンを表記する。GMS非対応の端末などは対応していないため切り分けのために必要。
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* アプリに関するお問い合わせを選択
* appsupport@cov19.mhlw.go.jpをタップ
* メールフォームを確認し、DEVICE_INFOが追記されていることを確認
```
DEVICE_INFO : APP_VERSION,Pixel 2 XL,(Google),Android,10
お名前：
ご連絡先：
お問い合わせ内容(カテゴリを次の中からお選びください)：1.アプリの仕組み、2.アプリの設定、 3.アプリの利用(通知など)、 …
```
> Fix #760 : お問い合わせメールにAPPデバイス情報とアプリバージョンを記載

- Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
陽性情報の入力(NotifyOtherPage)画面で登録ダイアログでキャンセルしたときのダイアログを削除し、ユーザーの操作の手間を1ステップ減らしました。
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* 登録ダイアログがdismissした後、キャンセルダイアログが表示されないこと
メッセージで'キャンセルしました'を表す言語リソースNotifyOtherPageDiag2Message については残しています。今後メッセージを他の場所で流用される可能性があるためです。
> Fix #725: 陽性情報の入力(NotifyOtherPage)画面 登録ダイアログでキャンセルしたときのダイアログは不要

- Covid19Radar/Covid19Radar/Views/HelpPage/HelpPage3.xaml
- Covid19Radar/Covid19Radar/Views/HelpPage/HelpPage4.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/HomePage.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/NotContactPage.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/SubmitConsentPage.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/ThankYouNotifyOtherPage.xaml
- Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
- Covid19Radar/Covid19Radar/Views/Settings/SettingsPage.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/PrivacyPolicyPage.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage1.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage2.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage3.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage4.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage5.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage6.xaml
UI 表示されているテキストと読み上げ音声が一致しない箇所があるので、その修正をしました。
関連Issue は#596 で、このプルリクエストではAndroid の一部を修正しました。
対応しきれなかったことは"Other Information" に記載しましたので、お手数ですがこちらもご確認のほどよろしくお願いします。
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
なし
Android 端末で下記の読み上げを試してみてください。
ファイル名 | UI 上の表示
--- | ---
HelpPage/HelpPage3.xaml | 「陽性情報の登録と他者への匿名通知へ」
HelpPage/HelpPage4.xaml | 「アプリの設定へ」
HomePage/HomePage.xaml | 「陽性者との接触を確認する」
HomePage/NotContactPage.xaml | 「アプリを周りの人に知らせる」
HomePage/NotifyOtherPage.xaml | 「登録する」
HomePage/SubmitConsentPage.xaml | 「同意して陽性登録する」
Settings/SettingsPage.xaml | 「使用中止」 …
> 【Android/iOS】読み上げテキストの設定修正

- Covid19Radar/Covid19Radar/Views/HelpPage/HelpPage3.xaml
* #696 の修正になります。HelpPage3にて使用されない画像リソースHelpPage43.pngがあったため、例外でブレークする設定の場合にブレークしていました。
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
1. "メイン画面"を開く
1. "使い方"を開く
1. "新型コロナウイルスに感染していると判定されたら"を開く
```
* 例外でブレークする設定でデバッグ実行し、HelpPage3を開いても当該例外でブレークしないこと
なし
> (優先度：低)(Critical?：No)Fix #696 - Remove an unused image resource in the HelpPage3

- Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
- Covid19Radar/Covid19Radar.Android/Properties/AndroidManifest.xml
Android App Bundle feature in release build
Download size will probably be reduced to 50MB+.
[Limitation]
For apps deployed to devices running Android versions between 6.0 Marshmallow (API level 23) and 8.1 Oreo (API level 28), this feature currently only works if the app has the android:installLocation attribute set to "internalOnly" in the Android manifest.
https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.4#initial-support-for-android-app-bundle-publishing-format
> [Feature]Android App Bundle feature in release build

- Covid19Radar/Covid19Radar/Behaviors/NumberOnlyBehavior.cs
- Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml
"陽性情報の登録"について、処理番号の入力欄に数字以外も入力できるようになっていました※
"登録する"ボタンをタップしたときに数字のみかどうかバリデーションされますが、番号入力時に制限しておくことで番号のみ入力できることを直感的にわかるようにしています。
※ 数字キーボードで入力する設定はされていましたが、入力直後の制限はありませんでした。また、"."が入力可能になっていました。
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
* 数字1桁を入力すると、そのまま入力欄に反映される
* 数字以外を入力しても、入力欄は更新されずそのままになる
```
* 入力欄には数字のみ入力できること
* 入力欄に数字以外を入力したとき、入力欄が更新されないこと
* …
> (優先度：中)(Critical?：Middle)処理番号の入力欄について、数字以外の入力を無効にする

- Covid19Radar/Covid19Radar.Android/BackgroundService/BootReceiver.cs
AndroidのminSDKVersionが23(Android M)のため、Lolipop(21)用の分岐は不要です。
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
Sorry, development environment construction in now.
* ...
rerate #580
> minSDKVersionが23のためLolipop(21)用のコードを削除
