Covid-19Radar/Covid19Radar

- README.ja.md
- README.md
add iOS install url, for en and ja.
> add install link for iOS.

- .gitignore
- Covid19Radar.Functions.Common/Models/UserModel.cs
- Tools/UpdateUserStatusTool/UpdateUserStatusTool.sln
- Tools/UpdateUserStatusTool/UpdateUserStatusTool/App.config.example
- Tools/UpdateUserStatusTool/UpdateUserStatusTool/Program.cs
- Tools/UpdateUserStatusTool/UpdateUserStatusTool/Properties/launchSettings.json
- Tools/UpdateUserStatusTool/UpdateUserStatusTool/UpdateUserStatusTool.csproj
#8 
This is a tool to check the behavior when you change UserStatus.
これは、UserStatus を変更した時の動作確認を行うためのツールです
> Add Tool for Update UserStatus

- Covid19Radar.Functions.Common/Models/BeaconModel.cs
- Covid19Radar/Covid19Radar.Android/Services/BeaconService.cs
- Covid19Radar/Covid19Radar.iOS/Services/BeaconService.cs
- Covid19Radar/Covid19Radar/Model/BeaconDataModel.cs
> Add Attributes BeaconModel

- Covid19Radar/Covid19Radar/ViewModels/UserSettingPageViewModel.cs
> fix PhoneNumber of Otp, format e164

- Covid19Radar/Covid19Radar/Colors.xaml
- Covid19Radar/Covid19Radar/Styles.xaml
- Covid19Radar/Covid19Radar/ViewModels/ConsentByUserPageViewModel.cs
- Covid19Radar/Covid19Radar/Views/ConsentByUserPage.xaml
> Add ActivityIndicator

- Covid19Radar.Functions.Common/DataStore/Cosmos.cs
- Covid19Radar.Functions.Common/DataStore/ICosmos.cs
- Covid19Radar.Functions.Common/Models/NotificationMessageModel.cs
- Covid19Radar.Functions.Common/Services/INotificationService.cs
- Covid19Radar.Functions.Common/Services/NotificationService.cs
- Covid19RadarAPI.Tests/Mock/CosmosMock.cs
- Covid19RadarAPI/BeaconApi.cs
- Covid19RadarAPI/Models/UserResultModel.cs
- Covid19RadarAPI/RegisterApi.cs
- Covid19RadarAPI/Startup.cs
- Covid19RadarAPI/UserApi.cs
- Covid19RadarAPI/local.settings.json.example
Add LastNotificationTime for result of UserApi.
Implement NotificationService in api
UserApi の結果に LastNotificationTime を追加します。
API内部のNotificationService を実装。
> Add LastNotificationTime for result of UserApi

- Covid19RadarAPI.Tests/Mock/NotificationServiceMock.cs
- Covid19RadarAPI.Tests/UserApiTest.cs
> Fix Build Error for Functions tests project

- Covid19Radar/Covid19Radar/Views/HomePage.xaml
> Scroll HOME page

- Covid19Radar.Functions.Common/Models/NotificationMessageModel.cs
- Covid19RadarAPI.Tests/Models/NotificationMessageModelTest.cs
> Modify NotificationMessageModel

- Covid19Radar.Functions.Common/Models/NotificationMessageModel.cs
- Covid19Radar.Functions.Common/Services/INotificationService.cs
- Covid19Radar.Functions.Common/Services/NotificationService.cs
- Covid19RadarAPI.Tests/Mock/NotificationServiceMock.cs
- Covid19RadarAPI/Models/NotificationPullParameter.cs
- Covid19RadarAPI/Models/NotificationPullResult.cs
- Covid19RadarAPI/NotificationPullApi.cs
> Implements NotificationPullApi

- Covid19Radar/Covid19Radar.Android/MainActivity.cs
- Covid19Radar/Covid19Radar.Android/Services/BeaconService.cs
- Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
- Covid19Radar/Covid19Radar/Model/NotificationMessageModel.cs
- Covid19Radar/Covid19Radar/Model/UserDataModel.cs
- Covid19Radar/Covid19Radar/Services/HttpDataService.cs
- Covid19Radar/Covid19Radar/Services/UserDataService.cs
Implement call NotificationPullApi.
fix Dependency Injection for ISQLiteConnectionProvider.
implement Notification into UserDataService.
remove call to PUT /api/User.
#67
> Implement call NotificationPullApi. #67

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hant.xlf
> Tranditional Chinese translation

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hans.xlf
> Simplified Chinese translation

- Covid19Radar/Covid19Radar.iOS/Services/BeaconService.cs
Fix #76 
Fixed sigabt to not occur...
> Fix BeaconService for iOS

- Covid19Radar/Covid19Radar.Android/Services/BeaconService.cs
- Covid19Radar/Covid19Radar.iOS/Services/BeaconService.cs
- Covid19Radar/Covid19Radar/Services/HttpDataService.cs
Fix abort BeaconService and HttpDataService when network error or http response not success.
#80
> Fix abort BeaconService and HttpDataService

- Covid19RadarAPI/NotificationCreateApi.cs
> Fix incorrect data mapping in NotificationCreateApi (#83)

- Covid19RadarAPI/NotificationCreateApi.cs
> Add parameter checking in NotificationCreateApi

- Covid19Radar/Covid19Radar/ViewModels/DetectedBeaconPageViewmodel.cs
> Convert LastDetectTime to local time

- Covid19RadarAPI/NotificationCreateApi.cs
> Use GUID instead of date time as notification ID

- Covid19RadarAPI.Tests/Mock/ValidationUserServiceMock.cs
- Covid19RadarAPI.Tests/UserApiTest.cs
#105 
build error on API.Tests
> Fix #105 build error on API.Tests

- src/Covid19Radar.Api/NotificationPullApi.cs
- src/Covid19Radar.Api/UserApi.cs
#108 
Modify, Get method implements functionality equivalent to post method
> Modify, Get method implements functionality equivalent to post method

- src/Covid19Radar.Api.Tests/BeaconApiTest.cs
- src/Covid19Radar.Api.Tests/RegisterApiTest.cs
- src/Covid19Radar.Api.Tests/UserApiTest.cs
- src/Covid19Radar.Api/BeaconApi.cs
- src/Covid19Radar.Api/DataAccess/CosmosBeaconRepository.cs
- src/Covid19Radar.Api/DataAccess/CosmosOtpRepository.cs
- src/Covid19Radar.Api/DataAccess/CosmosUserRepository.cs
- src/Covid19Radar.Api/DataAccess/IBeaconRepository.cs
- src/Covid19Radar.Api/DataAccess/IOtpRepository.cs
- src/Covid19Radar.Api/DataAccess/IUserRepository.cs
- src/Covid19Radar.Api/NotificationPullApi.cs
- src/Covid19Radar.Api/RegisterApi.cs
- src/Covid19Radar.Api/Services/OtpService.cs
- src/Covid19Radar.Api/Startup.cs
- src/Covid19Radar.Api/UserApi.cs
Replace **ICosmos** by repositories in the **Covid19Radar.Api** project
#110
> Introduct data access classes

- Covid19Radar/Covid19Radar/ViewModels/DetectedBeaconPageViewmodel.cs
> Fixed beacon.LastDetectTime.Kind condition.

- CONTRIBUTERS.md
テストユーザーの2020年5月3日時点での追加ユーザー分です！
> 20200503Update

- Covid19Radar/Covid19Radar/Resources/html/en/contributor.html
- Covid19Radar/Covid19Radar/Resources/html/en/privacypolicy.html
- Covid19Radar/Covid19Radar/Resources/html/en/qna.html
- Covid19Radar/Covid19Radar/Resources/html/en/update.html
- Covid19Radar/Covid19Radar/Resources/html/ja/contributor.html
- Covid19Radar/Covid19Radar/Resources/html/ja/privacypolicy.html
- Covid19Radar/Covid19Radar/Resources/html/ja/qna.html
- Covid19Radar/Covid19Radar/Resources/html/ja/update.html
> Fix HTML tags

- Covid19Radar/Covid19Radar/Resources/html/en/privacypolicy.html
- Covid19Radar/Covid19Radar/Resources/html/ja/privacypolicy.html
> Fix translations

- CONTRIBUTORS.md
> update: add Simplified Chinese translator to contributors

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.nl.xlf
Reviewed and updated the dutch translations.
> Update Dutch translations

- Covid19Radar/Covid19Radar/Resources/AppResources.et.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.it.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.nb.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.ta.resx
いくつか不必要と思われる < がありましたので、削除しました
> Delete unnecessary <

- README.md
Proto type -> Prototype
~ link.Currently ~ -> ~ link. Currently ~
> README.md Minor Fix

- CONTRIBUTORS.md
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.ar.xlf
- HOW_TO_TRANSRATE_CONTRIBUTE.md
- README.md
- Completed the Arabic translation.
- Fixed some typos.
- Updated the list of contributors to include myself.
> Arabic translation

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.it.xlf
> Update Italian translation

- .github/ISSUE_TEMPLATE.md
> Please provide us with the following information:
> ---------------------------------------------------------------
```
```
> Template should be added when new PR is created
>No
> 
1. Create PR
2. Check overview
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
1. macOS
This was only tested on my branch because this cannot really be tested on master or with unittest/integration test.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.
> Add issue template for PR

- Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
- Covid19Radar/Covid19Radar/Resources/AppResources.en.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
- Covid19Radar/Covid19Radar/Views/Tutorial/PrivacyPolicyPage.xaml
> Multilingual localization

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.af.xlf
Updated corrected the Afrikaans translations
> Updated/Corrected Afrikaans Translations

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.th.xlf
Finished 1st reviewed on Thai translation. 
I admitted that 'Exposure Notification' is quite hard to translated. So I translated its into the words that mean 'Expose your contact activity'.
> 1st Thai language translation reviewed

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.vi.xlf
Just review & update the translation to VN. Please take a look with thanks.
Best,
Phi
> #51 vi translation resource file translation

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.nl.xlf
* Fix NL Translation xlif parse error
```
[X ] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
```
* Covid19Radar.nl.xlf  Download Get the code
Open MUI(Multilingual Editor Tool Kit)
```
```
* ...
> Fix NL Transration format error

- CONTRIBUTORS.md
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.id.xlf
> Fix Indonesian Translation

- Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
> Fix multilingual localization

- Covid19Radar/Covid19Radar/Resources/AppResources.bg.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.el.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.fi.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.hr.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.ko.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.ru.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.th.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hant.resx
* Fix App name - COVID-19Radar
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix App name

- Covid19Radar/Covid19Radar/Common/HoursTimer.cs
- Covid19Radar/Covid19Radar/Common/MinutesTimer.cs
- Covid19Radar/Covid19Radar/Services/UserDataService.cs
- Covid19Radar/Covid19Radar/ViewModels/Tutorial/PrivacyPolicyPageViewModel.cs
* Fix typo
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
> Fix typo "register"

- Covid19Radar/Covid19Radar/App.xaml.cs
- Covid19Radar/Covid19Radar/Covid19Radar.csproj
- Covid19Radar/Covid19Radar/ViewModels/HomePage/UpdateInformationPageViewModel.cs
- Covid19Radar/Covid19Radar/ViewModels/MenuPageViewModel.cs
- Covid19Radar/Covid19Radar/Views/HomePage/UpdateInformationPage.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/UpdateInformationPage.xaml.cs
- Covid19Radar/Covid19Radar/Views/UnUsed/MainPage.xaml
* Fix typo
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
> Fix typo "information"

- Covid19Radar/Covid19Radar/Model/UserDataModel.cs
* Fix #253 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix build error

- Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
- Covid19Radar/Covid19Radar/App.xaml.cs
- Covid19Radar/Covid19Radar/Covid19Radar.csproj
- Covid19Radar/Covid19Radar/ViewModels/HomePage/SettingsPageViewModel.cs
- Covid19Radar/Covid19Radar/ViewModels/Tutorial/InitSettingPageViewModel.cs
- Covid19Radar/Covid19Radar/ViewModels/ViewModelBase.cs
- Covid19Radar/Covid19Radar/Views/Tutorial/DescriptionPage1.xaml
- Fix Tutorial1  image
- Add Exposure Notification Enable Dialog
> Wire exposure notification

- HOW_TO_CONTRIBUTE.md
* Add contribute rules
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Add contribute rules

- .github/workflows/deployfunctions.yml
- CONTRIBUTORS.md
Fix azure function deployment
* ...
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* Builds in https://github.com/Covid-19Radar/Covid19Radar/actions becomes green
> Fix nuget packages restore in deployfunctions.yml

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.af.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.es.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.fr.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.it.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.ja.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.nl.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.th.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.tr.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hans.xlf
* Fix format
`<target state="translated" state-qualifier="tm-suggestion">` -> `<target state="translated">`
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix format

- .github/workflows/deployfunctions.yml
* Fix project path in the deployment script
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
Run github action on https://github.com/Covid-19Radar/Covid19Radar/actions?query=workflow%3A%22Deploy+Covid19+to+Azure+Functions%22 on the PR
```
* Check if the job becomes green
> Fix API project path in deployfunctions.yml

- Covid19Radar/Covid19Radar/App.xaml.cs
* Fix type and build error in #277 
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
```
```
Build
```
* Build successfully
> FIx typo and build error

- Covid19Radar/Covid19Radar.Android/Properties/AndroidManifest.xml
* Fix mistake COVID-19Radar -> Covid19Radar ( #242 ) -> COVID-19Radar
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix mistake

- Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
* Add platform: x86
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Add platform

- Covid19Radar/Covid19Radar/Services/UserDataService.cs
- Covid19Radar/Covid19Radar/ViewModels/ViewModelBase.cs
- ViewModel Overload
- Change JumpHash
> Change to JumpHashSeed and overload args

- Covid19Radar/Covid19Radar/App.xaml.cs
- Covid19Radar/Covid19Radar/ViewModels/ViewModelBase.cs
Fix EN and UserData Referencebug
```
[X ] Bugfix
[ ] Feature
```
> Fix EN and UserData Referencebug

- Covid19Radar/Covid19Radar.Android/Properties/AndroidManifest.xml
- Covid19Radar/Covid19Radar.iOS/Info.plist
* Fix version format: x.y -> x.y.z
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix version format: x.y.z

- Covid19Radar/Covid19Radar/ViewModels/HomePage/SettingsPageViewModel.cs
Delete git submodules
```
[X ] Yes
[ ] No
```
> delete sub modules

- Covid19Radar.sln
- Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
- Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
- Covid19Radar/Covid19Radar/Covid19Radar.csproj
Update EN nuget
Remove reference Xamarin.Exposure Notification
> Renew Nuget EN

- Covid19Radar/Covid19Radar.Android/Services/CloseApplication.cs
* Forms.Context is obsolute. change to Xamarin.Essentials ( Platform.CurrentActivity )
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
> Avoid warining Forms.Context => Platform.CurrentActivity

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.ja.xlf
- Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
- Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.resx
- Covid19Radar/Covid19Radar/Views/HelpPage/InqueryPage.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/HomePage.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/TermsofservicePage.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage2.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage5.xaml
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Updated my part

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.ja.xlf
- Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
- Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.resx
- Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml
- Covid19Radar/Covid19Radar/Views/MenuPage.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage1.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage4.xaml
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Updated NotifyOtherPage.xaml, TutorialPage1.xaml, TutorialPage4.xaml, MenuPage.xaml 

- Covid19Radar/Covid19Radar/Templates/HelpMenuTemplate.xaml
- Covid19Radar/Covid19Radar/Views/HelpPage/HelpMenuPage.xaml
* Small improvement of UI in help menu page
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Improve UI
```
Android emulator snapshot before editing:
Android emulator snapshot after editing:
> Small improvement of UI in help menu page

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.ar.xlf
I began reviewing the Arabic translation. I made some changes till line 170 and will continue tomorrow
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Updated Covid19Radar.ar.xlf  for better Ar Trans.

- Covid19Radar/Covid19Radar.Android/appcenter-pre-build.sh
Auto Generate and Replace App Id
> Auto generate App ID

- CONTRIBUTORS.md
- README.ja.md
- README.md
The link of cotributing guide file in README is wrong. Let's fix it up.
Closes #420 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
Check HTTP link.
Verify that the URL is valid.
> Correct wrong link in README.md

- Covid19Radar/Covid19Radar/Common/AppConstants.cs
> Delete unused coinstant

- Covid19Radar/Covid19Radar/Views/HomePage/ChatbotPage.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/PrivacyPolicyPage2.xaml
- Covid19Radar/Covid19Radar/Views/HomePage/TermsofservicePage.xaml
- Covid19Radar/Covid19Radar/Views/NavigatePopoverWebView.cs
- Covid19Radar/Covid19Radar/Views/Settings/LicenseAgreementPage.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/PrivacyPolicyPage.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage3.xaml
[Fix]Webview Navigate issue
[Fix][iOS]WebView Auto-Height
> [Fix]Webview issues

- README.ja.md
- README.md
> modify README

- CONTRIBUTING.md
As described in #429 , remove the step as we cannot do it. 
This is just a proposal PR.
Closes #429 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
Check modified md.
> Remove "Apply label" step from CONTRIBUTING.md

- Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
- Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
Add English image resources file
> Add Images

- Covid19Radar/Covid19Radar/App.xaml
- Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
- Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml
HERSYS cooperation interface will be opened at a later date.
> Marge HERSYS link disabled

- CONTRIBUTORS.md
- README.md
* Fix "C #" to "C#"
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
> Fix expression in README.md

- Covid19Radar/Covid19Radar/App.xaml.cs
- Covid19Radar/Covid19Radar/Model/UserDataModel.cs
- Covid19Radar/Covid19Radar/ViewModels/Tutorial/TutorialPage6ViewModel.cs
> windowFlowControl

- Covid19Radar/Covid19Radar/Views/Tutorial/PrivacyPolicyPage.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage1.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage2.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage3.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage4.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage5.xaml
- Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage6.xaml
Fix TutorialPages for big font setting or small screen devices.
- Scroll contents and bottom buttons without title.
- Buttons on pages that use WebView do not scroll.
- XAML cleanup.
> [Fix]TutorialPages for big font setting or small screen devices.

- CONTRIBUTING.md
- README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> chore: refactor to correct grammar (noun)

- COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
- Covid19Radar/Covid19Radar/Resources/html/license.html
- Covid19Radar/Covid19Radar/Resources/html/license.md
* To fix small part in License files. The sentence in app looks wrong.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
Since this is documentation fix, there is no code to test
* Nothing. Sorry I don't have resource to build this app.
> Fix sentences in license files

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hans.xlf
* ...
一部の中国語簡体字の翻訳を追加しました。
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Chinese Localization
```
```
cd [repo-name]
npm install
```
```
```
* ...
> update: add some Chinese translation

- CONTRIBUTORS.md
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hant.xlf
* Improve Traditional Chinese translation.
* Adjusting the words to fit the usage of traditional Chinese users
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: i18n
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Translation for Traditional Chinese

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.de.xlf
This PR contains the German translation and resolves #35.
[ ] Yes
[x] No
```
[ ] Bugfix
[x] Feature
[x] Other... Please describe: localization
```
~This PR is still work on progress and the localization is not 100% complete yet.~
> German translations

- README.md
Unfortunately, "Japanese only" sometimes means "Japanese people only, Non-Japanese is not welcome".
e.g. https://twitter.com/sanji_kinchan/status/1229568258145021954
I hope that the project is not for only Japanese people, but also all people.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
N/A
N/A
ref. https://ha2.seikyou.ne.jp/home/Kazuma.Kohara/nojo.htm
ref. http://next49.hatenadiary.jp/entry/20140428/p1
> fix misleading sentence: "Japanese only"

- CONTRIBUTORS.md
- README.md
* There is a grammar miss in readme.md.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Grammar correction

- CONTRIBUTORS.md
- doc/Developer-Node.md
- doc/FAQ-on-Mobile-App-build-failed.md
- close #489 
- Fix some broken image's links.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
Check if the image is displayed correctly in the following two files: 
- [Developer-Node.md](https://github.com/Covid-19Radar/Covid19Radar/blob/3ebc6bc3967c6e26a1c8e351dc9665577753e534/doc/Developer-Node.md)
- [FAQ-on-Mobile-App-build-failed.md](https://github.com/Covid-19Radar/Covid19Radar/blob/3ebc6bc3967c6e26a1c8e351dc9665577753e534/doc/FAQ-on-Mobile-App-build-failed.md)
> fix broken links

- Covid19Radar/Covid19Radar/ViewModels/HelpPage/InqueryPageViewModel.cs
Closes #479 
Mail Body Bug fix
> Fix Mail Message

- Covid19Radar/Covid19Radar/Resources/html/en/termofuse.html
- Covid19Radar/Covid19Radar/Resources/html/en/termofuse.md
* Apply a strong style to some headlines in en/termofuse.
* I didn't know how to generate html files, so I directly edited some files for now.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
* None
* None
> Fix document style

- Covid19Radar/Covid19Radar/Resources/html/en/privacypolicy.md
- Covid19Radar/Covid19Radar/Resources/html/en/termofuse.html
- Covid19Radar/Covid19Radar/Resources/html/en/termofuse.md
> Fix docs style

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.es.xlf
* Fixings for spanish translation (スペイン語の翻訳の修正)
* Use same word for important terms. For example "処理番号" now is "número de procesamiento" in all places. "接触" close contact is "contacto cercano" in all places. "管理システム" now is "systema de gestion" in all places.
* Other minor translation fixes (mostly to be uniform with other text's nuances)
```
[ ] Yes
[●] No
```
```
[● ] Bugfix
[ ] Feature
[●] Other... Please describe: Translation file update only
```
> Fixes for spanish translation

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.id.xlf
* Update on Indonesian translation.
[ ] Yes
[x ] No
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Translation/Localization
Is there any further guidance on what should be done with the string "TutorialPage2Description1"?
> Update on Indonesian translation (Covid19Radar.id.xlf)

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.id.xlf
* Indonesian translation update based on the latest Multilingual Localization file of Covid19Radar.id.xlf,
* Another changes in translation for clarity and consistency.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe: Update on Indonesian Localization
```
* Translation for the string "TutorialPage2Description1" is being left out as it was.
> Indonesian translation update based on the latest Multilingual Localization file of Covid19Radar.id.xlf

- Covid19Radar/Covid19Radar/Model/UserDataModel.cs
- Covid19Radar/Covid19Radar/Services/ExposureNotificationService.cs
- Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
Fixed a crash when opening HomePage in Arabic setting(#493).
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
1. Set the app's language setting to Arabic.
1. Finish all turorials.
1. Open the HomePage.
1. Confirm that app doesn't crash.
```
* App doesn't crash in Arabic setting when opening HomePage.
* Proper debugging output in ExposureNotificationService.OnTimerInvoked().
> Fix datetime crashes on arabic

- Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
- Covid19Radar/Covid19Radar.iOS/Extensions/FontExtensions.cs
- Covid19Radar/Covid19Radar.iOS/Main.cs
- Covid19Radar/Covid19Radar.iOS/Properties/AssemblyInfo.cs
- Covid19Radar/Covid19Radar.iOS/Services/CloseApplication.cs
- Covid19Radar/Covid19Radar.iOS/Services/DeviceCheckService.cs
Xamarin.iOS project contains never remove-un-used import files.
So, I just remove that.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> [iOS] remove un-use import for iOS

- .github/workflows/infrastructure.yml
- infrastructure/01_init/main.tf
- infrastructure/01_init/variables.tf
- infrastructure/02_runtime/main.tf
- infrastructure/02_runtime/provider.tf
- infrastructure/02_runtime/variables.tf
- Add infrastructure/terraform github actions
- Run `terraform fmt` for best practices
- Implement proper ci/cd
Related: https://github.com/Covid-19Radar/Covid19Radar/pull/453
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Add terraform github actions (with fmt, init, validate)

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hans.xlf
* Simplified Chinese Translation Reviewed
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Translation
```
> Simplified Chinese Translation Reviewed

- Covid19Radar/Covid19Radar.Android/Properties/AndroidManifest.xml
- Covid19Radar/Covid19Radar.iOS/Info.plist
Update versionName / CFBundleShortVersionString to 1.1.0
> Update versionName / CFBundleShortVersionString to 1.1.0

- Covid19Radar/Covid19Radar/Views/HelpPage/InqueryPage.xaml
> Marge sub number

- Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
Use aapt2 in release build setting.
> Fix for android release build issue.

- doc/Developer.md
* Ref #527
* This PR has a draft document. 
I would like to collect the information based on it.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
None.
* This document's file name, file path
* OS, IDE, SDK version
This document is draft.
Any comment are welcome.
> The building guide of development environment for software developer

- Covid19Radar/Covid19Radar.Android/Properties/AndroidManifest.xml
- Covid19Radar/Covid19Radar.Android/appcenter-pre-build.sh
- Covid19Radar/Covid19Radar.iOS/Info.plist
- Covid19Radar/Covid19Radar.iOS/appcenter-pre-build.sh
- Covid19Radar/Covid19Radar/settings.json
Replace plist and manifest
2020 02 50
> Replace plist and manifest

- Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
- Covid19Radar/Covid19Radar.iOS/appcenter-pre-build.sh
Fix Build Issue / Check Android
> Fix Build Issue

- Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
Call FetchExposureKeyAsync when displaying HomePage.
> [Feature] Call FetchExposureKeyAsync when displaying HomePage.

- Covid19Radar/Covid19Radar/Model/UserDataModel.cs
- Covid19Radar/Covid19Radar/Model/UserExposureInfo.cs
- Covid19Radar/Covid19Radar/Model/UserExposureSummary.cs
- Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
- Covid19Radar/Covid19Radar/Services/UserDataService.cs
- Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> Wire notification RC

- Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
Case Exception Device not have a diag keys
> Exception Device not have a diag keys

- CONTRIBUTORS.md
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.th.xlf
- Update Thai translation to be better for user to understand.
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[X ] Other... Please describe: Translation update.
```
> Update Thai translation.

- doc/Developer.md
* Ref #527
* Merged #571 by Core Contributor, but i couldn't find `doc/Developer.md`. Thus i retry.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
None.
* This document's file name, file path
* OS, IDE, SDK version
This document is draft.
Any comment are welcome.
> [Retry] The building guide of development environment for software developer

- Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
[Fix]Navigation fix from NotifyOtherPage to HomePage
> [Fix]Navigation fix from NotifyOtherPage to HomePage

- Covid19Radar/Covid19Radar/AppSettings.cs
- Covid19Radar/Covid19Radar/Model/UserDataModel.cs
- Covid19Radar/Covid19Radar/Resources/AppResources.th.resx
- Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
- Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
- Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
- Fetch UserDataModel from UserDataService
- Update UserDataModel EventHandler
> FixUserStateBug

- Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
> Fix Label Position

- src/Covid19Radar.Api.Common/Services/CryptionService.cs
Google reference server haven't checked the reference too!!! :(
> Padding Check Off

- Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
> remove padding

- Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
- src/Covid19Radar.Api.Common/Services/CryptionService.cs
> RevertReset

- Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
- src/Covid19Radar.Api.Common/Services/CryptionService.cs
Go to Release Version 2
/*
* Our mission...is
* Empower every person and every organization on the planet achieve more.
* Put an end to Covid 19
*/
> Go to Release

- Covid19Radar/Covid19Radar.Android/Properties/AndroidManifest.xml
Android WorkMamanager remove , to use xamarin exposure notificaation side generated
> Remove from manifest

- README.ja.md
- README.md
新たに追加された開発ドキュメントを他の方が見つけやすいようにREADMEにリンクを追加しました。
お手隙でレビューいただければ幸いです。
関連issue: #527
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
* リンクをタップして開発ドキュメントが開けること
* 追加したリンクの位置がREADME.mdの「Development environment」の項で問題ないかの確認
> READMEに開発ドキュメントのリンクを追加

- src/Covid19Radar.Background/Services/TemporaryExposureKeyExportBatchService.cs
* ...
```
[ ] Yes
[x] No
```
```
[x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix Export file names, and fix batchnum and batchsize in export.bin

- COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
- Covid19Radar/Covid19Radar/Resources/html/license.md
https://github.com/FortAwesome/Font-Awesome
https://github.com/googlefonts/noto-cjk
https://github.com/googlefonts/roboto
https://github.com/Templarian/MaterialDesign-Webfont
#686
Add licenses for font used in this project.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
N/A
Check the documents.
[license.html](https://github.com/Covid-19Radar/Covid19Radar/blob/master/Covid19Radar/Covid19Radar/Resources/html/license.html) は生成方法が分からなかったので修正していません。
> Add font licenses

- COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
#684
Fix Covid19Radar License in COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
N/A
Check the document.
https://github.com/Covid-19Radar/Covid19Radar/blob/23d116eed36ca8d7700aa8ef8a999265aab3b8ea/Covid19Radar/Covid19Radar/Resources/html/license.md
> Fix License

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.fr.xlf
- Covid19Radar/Covid19Radar/Resources/AppResources.fr.resx
* Update fr translation of MenuPageTitle
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
|before|after|
|-|-|
|<img width="270" src="https://user-images.githubusercontent.com/19593968/85531551-d6277780-b649-11ea-8cf9-80fc2bd11014.png">|<img width="270" src="https://user-images.githubusercontent.com/19593968/85531600-e0497600-b649-11ea-872e-a1d1709242b5.png">|
> Update fr translation MenuPageTitle

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.id.xlf
Indonesian translation update based on change at 26th June
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe: Translation/Localization
```
- none
> Indonesian translation update to Covid19Radar.id.xlf based on 26th June changes 

- Covid19Radar/Covid19Radar/App.xaml
#637 の対応
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
環境エラー
```
cd [repo-name]
npm install
```
```
```
*  App.xaml を編集して保存した時に自動生成でエラーがでないことを確認。
App.xamlのxmlnsのprismの指定がurlだと機能しないようでした。
他のページではurl指定のままで問題ありませんでした。
> fix XamlG error #637

- CONTRIBUTORS.md
- doc/Developer.md
* #527 に関連してインストール方法を更新しました。
* 開発マシンとしてMacを利用する開発者向けに[homebrew-cask](https://github.com/Homebrew/homebrew-cask)によるインストール方法を追記しました。
* Xamarinに馴染みの少ないAndroid/iOSネイティブアプリ開発者が手短に開発環境を構築できるようになることを期待した(ネイティブアプリ開発者を呼び込むための)PRです。
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
```
* Visual Studioから`Covid19Radar.sln`を開き、Android、iOSそれぞれについてマニュアルビルドした後、アプリ起動することを確認
* Android: CovidRadar.Android -> Debug_Mock
* iOS: CvodidRadar.iOS -> Debug_Mock | iPhone Simulator
Verify …
> Update installation manual using homebrew cask

- Covid19Radar/Covid19Radar/ViewModels/MenuPageViewModel.cs
- Covid19Radar/Covid19Radar/Views/MenuPage.xaml
Reverts Covid-19Radar/Covid19Radar#661
> Revert "#660対応 メニュー画面の選択セルの色が戻らない不具合を修正"

- Covid19Radar/Xamarin.ExposureNotification/CallbackService.android.cs
[Feature][Android] Add log ACTION_EXPOSURE_NOT_FOUND broadcast intent.
> [Feature][Android] Add log ACTION_EXPOSURE_NOT_FOUND broadcast intent.

- doc/HOW_TO_USE_YOUR_COUNTRY.md
Git Hub to GitHub
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
> minor fix in docs

- src/Covid19Radar.Background/Services/TemporaryExposureKeyExportBatchService.cs
* fix created timestamp for list.json
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* An amendment that assumes that the key provided should be provided by one person with multiple TEK.
> fix tek timestamp for list

- Covid19Radar/Covid19Radar/Model/DiagnosisSubmissionParameter.cs
- Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
- src/Covid19Radar.Api/Models/DiagnosisSubmissionParameter.cs
- src/Covid19Radar.Background/Services/TemporaryExposureKeyExportBatchService.cs
> Fix Some validator

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.pt.xlf
* Better portuguese translation
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Correct translation
```
```
git clone https://github.com/xX-TheDoctor-Xx/Covid19Radar
```
```
Run the app in portuguese language
```
* Translation has the correct context, check for any missing accents or words that can be misinterpreted
Look in the file for notes with the from tag value of "translator" and check what can be done there, there is some sentences that are not correctly formed in english and some words that …
> Update Portuguese translation

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.fr.xlf
* Reviewed and fixed some of the strings in French
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
> Fix and review FR translation

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hant.xlf
* #676 Review and update translation in zh-Hant
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Issue 676: Review and update translation in zh-Hant

- Covid19Radar/Covid19Radar/Model/PositiveDiagnosisState.cs
- Covid19Radar/Covid19Radar/Model/UserDataModel.cs
- Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
> Disable shared flg

- src/Covid19Radar.Background/TemporaryExposureKeyDeleteBatch.cs
- src/Covid19Radar.Background/TemporaryExposureKeyExportBatch.cs
* ...
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> modify timer trigger for export and delete batch

- src/Covid19Radar.Api.Common/DataAccess/CosmosTemporaryExposureKeyExportRepository.cs
* ...
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix miss match deleting keys.

- src/Covid19Radar.Background/TemporaryExposureKeyDeleteBatch.cs
> fix delete batch timer.

- doc/Developer-Note.md
* #756 doc/Developer-Note.md内の誤植と表示崩れが起きていたので修正しました。
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* doc/Developer-Note.mdを閲覧し #756 の2箇所の表記が修正されていること。
> Fix #756 : doc/Developer-Note.md内の誤植と表示崩れの修正

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.en.xlf
#750  Review and update translation in en-Hant
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix 750: Review and update translation in English

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.de.xlf
- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.en.xlf
#752 Review and update translation in de-Hant
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
Exposure NotificationをExpositionsmeldungで訳しています。意味は十分伝わるはずですが、アプリの中で一種の固有名詞扱いになるかと思うので、もしアプリ上で他の表記があればそちらに統一します。
> Fix752 Review and update translation in German

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.zh-Hans.xlf
* Update Chinese translation
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: i18n
```
```
cd [repo-name]
npm install
```
```
```
* ...
> update: Chinese translation

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.en.xlf
- Covid19Radar/Covid19Radar/Resources/AppResources.en.resx
以下のラベルがついた PR について一つ一つマージ後のビルド確認をしました。
https://github.com/Covid-19Radar/Covid19Radar/pulls?q=is%3Apr+is%3Aclosed+label%3ACheckRestore
その中から、ビルドエラーや大量のコンフリクトが発生する PR を除いた PR を最新 master に反映した PR を作成しました。
以下がマージ内容です
#751: コンフリクトが発生しましたが、対応しました。またPRが不正な状態だったため、それを訂正する修正を追加で入れています。
> Check restore pull request

- CONTRIBUTORS.md
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update CONTRIBUTORS
```
> Added myself to CONTRIBUTORS list

- Covid19Radar/Covid19Radar/MultilingualResources/Covid19Radar.pt.xlf
Merge latest changes of the portuguese translation
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: translation
```
> Finished translation - needs review for certain strings

- CONTRIBUTORS.md
- Covid19Radar/Covid19Radar/Resources/html/license.html
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
* ライセンス内に無関係なドメインへのリンクが含まれてないことを確認する。
`<h2 id="jsonnet"><a href="http://Json.NET">Json.NET</a></h2>` --> `<h2 id="jsonnet">Json.NET</h2>`
https://github.com/cocoa-mhlw/cocoa/issues/9
> Update license.html ライセンス内に無関係なリンクを削除
